name: DisableSpawnEggs
version: '${project.version}'
main: me.lukasabbe.disablespawneggs.DisableSpawnEggs
api-version: '1.20'
commands:
  DisableSpawnEggs:
    description: All settings for command
    aliases: DSE
    usage: /<command> [reload]
    permission: DSE.reload